### ISSUE TITLE
transfer speed

### ISSUE THREAD

**Issue by brunoalbertopeixoto** [mehrvarz/webcall#30]
I found the file transfer speed too slow.  I did the streaming test on Google's WebRTC and the speed was much better.  Another observation, sometimes the button to send files does not appear when in the browser.

**Comment by mehrvarz** [comment]
I just send a file with an average speed of 9142 KB/s (9+MB/s). One has to keep in mind that all data is being encrypted by the sender and decrypted by the receiver. A very slow CPU may be a limiting factor. But normally your ISP (or the ISP on the other side) will be the limiting factor, not WebCall/WebRTC. In fact, because you are sending data P2P I would argue that it is difficult to find a quicker file transfer method.

Can you provide your KB/s numbers? They are shown during file transfer.

**Comment by brunoalbertopeixoto** [comment]
I made a comparison: https://webrtc.github.io/samples/src/content/datachannel/filetransfer/

![Screenshot_2022-12-09-20-15-29](https://user-images.githubusercontent.com/41241891/206811166-66853bd4-954e-4a59-8ec8-c656941bbb87.png)
![Screenshot_2022-12-09-20-20-02](https://user-images.githubusercontent.com/41241891/206811181-4a96bc02-bafd-4582-b2db-4c1d17b312b9.png)

**Comment by mehrvarz** [comment]
In WebCall client you are shown 116 KB (kilobytes) per sec. In the other screenshot you are shown 1337 kbits (kilobits) per sec. Over the wire 10 bits = 1 byte of actual data. If you consider this then both images are showing about the SAME transfer speed. Unless there is a super slow device involved (encryption!), the limiting factor is the pipe.

**Comment by brunoalbertopeixoto** [comment]
you are right. I hadn't noticed that technical detail.

**Comment by mehrvarz** [comment]
Please re-open if needed.
