### ISSUE TITLE
ws-connect timeout in LAN test

### ISSUE THREAD

**Issue by zxkmm** [mehrvarz/webcall#5]
### I got a ws-connect timeout problem when I was testing in a local area network.

# what I plan to do
1. Build webcall server
2. Use NAT traversal service to use webcall on the internet.
# what happened
1. Build webcall server on an orange pi zero 2 (a Raspberry Pi like device), succeed.
2. Webcall build succeed
3. Using this `config.ini` below, tested in localhost with http, **works fine**.
```
hostname = 127.0.0.1
httpsPort = 8068
wssPort = 8443
insecureSkipVerify = true
```
4. Using this `config.ini` below, tested in localhost with HTTP, self-signed certificate, **works fine**.
```
hostname = 127.0.0.1
httpsPort = 8068
wssPort = 8443
insecureSkipVerify = true
```
5. Using this `config.ini` below, test in LAN, not able to `Go Online` using a machine in LAN. Error log shows `
/login ws-connect timeout 30s remove xxxxxxxxxxx/xxxxxxxxxxx xxxxxxxxxxx rip=192.168.0.105:58573 ver= ua=xxxxxx
`
```
hostname = 192.168.0.112
httpsPort = 8068
wssPort = 8443
insecureSkipVerify = true
```
6. Tried many NAT traversal service, using this `config.ini`, same problem.
```
hostname = 127.0.0.1
httpsPort = 8068
wssPort = 8443
insecureSkipVerify = true
```
# Environment
Orange pi zero 2
Debian 10
go1.17 linux/arm64
Firefox

**Comment by mehrvarz** [comment]
Hi @zxkmm. Conceptually, WebCall server needs to be operated/hosted without NAT constrains, so that it can provide signalling/connectivity service to clients that may indeed have NAT constrains. I have not fully thought this through ("Use NAT traversal service to use webcall on the internet"), but I am a little sceptical about it.

Connect/login sequence starts over http(s) and transitions to websocket. "ws-connect timeout" indicates that http(s) is working, but a client is not communicating back to the server via websocket. After a certain time the server gives up waiting. A firewall might cause "ws-connect timeout" issue. Usually this happens on the client side, but here (based on your info) the problem could be on the server side.

"ws-connect timeout" may also occur if a client falls asleep during the login process, say, caused by Android doze mode (possibly triggered by battery optimizations). But this can be ruled out if you run the client on a desktop type device. So the question is why websocket communication (wssPort = 8443) from client to server does not work in step 5.

**Comment by zxkmm** [comment]
@mehrvarz Thank you very much for your help!    
I realized it is surely not possible to use a NAT traversal service to have webcall work on internet after your remind. I'll try to find other solution. Thx:)

And about the ws-connect, at first i suspect that is was caused by firewall like it forbidden port 8443 or something. But in iptables it seems that webcall had currently using port 8443, so after your remind i realized it might be a compatibility issues which us caused by my hardware or system. I'll check it. 
But i can be sure it is not caused by the client eg. Android doze or browser problem, cuz i tested it on many devices including iOS and windows and it never connect correctly.

I'll close this issue cuz i realized the problem is on me. And when i found a perfect solution, I'll post it here.
Thank you for your help again, and have a nice day! :)
