### ISSUE TITLE
Running as a non-root user (enhancement request)

### ISSUE THREAD

**Issue by grantbacon** [mehrvarz/webcall#8]
Running as non-root user yields:

>  tls.LoadX509KeyPair err=(open tls.pem: permission denied)

I believe this is because it needs the certs to run the websocket server (let me know if im wrong) which is not and cannot (?) be proxied through nginx

Given that LetsEncrypt requires frequent renewals, and some people such as myself automate certbot using cron jobs,  Thus, I opted to symlink the certs inside my webcall deployment so they remain unaffected when they change. 

While I understand workarounds may exist like copying and altering the permissions of the files, they do require maintenance as well as leniency on security.

Perhaps if detected that EUID is 0 it can read TLS files into memory then de-escalate to a specified user from config.ini? Just first thing that came to mind.

**Comment by mehrvarz** [comment]
It is important for me to point out that WebCall server works fine without being root. Yes, not every user may be able to read the cert from it's original location (or via symb link). There are multiple ways to solve this. I just don't see a "perfect" solution I would want to suggest.

**Comment by mehrvarz** [comment]
I was thinking about this again.

> I opted to symlink the certs inside my webcall deployment so they remain unaffected when they change.

WebCall server needs to be restarted in order to take advantage of a renewed cert. All websocket sessions need to wind down before they can start up again. There is no way around this.

Because there are potentially people connected to the server at any time, it is almost impossible to automate this process. Even more so if some are using the TURN service. Restarting the TURN service means to cut off all relayed connections.

To me, a renewed cert means work. The process includes waiting for the best moment to restart the server. The physical location of the cert files is really not the biggest concern.

I hope this explains better why it is difficult for me to suggest "a perfect" (automated) solution to this problem.
